site_name: API AVM Gateway

theme:
  name: material
  logo: ./assets/images/logo.svg
  favicon: ./assets/images/eemovel_favicon.png
  language: pt
  icon:
    admonition:
      note: octicons/tag-16
      warning: octicons/alert-16
      question: material/code-json
  features:
    - content.code.copy
    - navigation.top

nav:
  - 'index.md'
  - Endpoints:
    - Report PDF: 'endpoints/get_report_pdf.md'
    - Valuation Status: 'endpoints/get_valuation_status.md'
    - Valuation: 'endpoints/get_valuation.md'
    - Start Valuation: 'endpoints/post_start_valuation.md'



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - ./stylesheets/extra.css